-- AlterTable
ALTER TABLE "DiplomaResult" ADD COLUMN     "gpa4" DOUBLE PRECISION,
ADD COLUMN     "gpa5" DOUBLE PRECISION,
ADD COLUMN     "gpa6" DOUBLE PRECISION,
ADD COLUMN     "gpa7" DOUBLE PRECISION;
